/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espe.militarydininghall.view;

/**
 *
 * @author Eduardo Segarra, TheJavaBandits, DCCO-ESPE
 */
public class FrmAdminMenu extends javax.swing.JFrame {

    /**
     * Creates new form FmMilitaryDinindHallSystem
     */
    public FrmAdminMenu() {
        initComponents();
    }

    public FrmAdminMenu(String adminName) {
        initComponents();
        lbldNameAdmin.setText("Welcome, " + adminName + "!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        lbldNameAdmin = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblAccountBalance = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblBreakfast = new javax.swing.JLabel();
        lblLunch = new javax.swing.JLabel();
        lblDinner = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuMilitaryDiningHall = new javax.swing.JMenu();
        itmLogout = new javax.swing.JMenuItem();
        itmExit = new javax.swing.JMenuItem();
        mnuAdministrationOfTheUsers = new javax.swing.JMenu();
        itmEditRegister = new javax.swing.JMenuItem();
        itmUpdateTheAccountBalanceForACommensal = new javax.swing.JMenuItem();
        mnuDayManagment = new javax.swing.JMenu();
        itmBookADay = new javax.swing.JMenuItem();
        itmCancelADayBooking = new javax.swing.JMenuItem();
        itmSeeReservation = new javax.swing.JMenuItem();
        mnuHelp = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenu2.setText("jMenu2");

        jMenu5.setText("jMenu5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbldNameAdmin.setText("Welcome! ");

        jLabel4.setText("Your account balance is:");

        lblAccountBalance.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAccountBalance.setText("jLabel5");

        jLabel2.setText("$");

        jLabel3.setText("This month the dishes are:");

        jLabel5.setText("Breakfast:");

        jLabel6.setText("Lunch: ");

        jLabel7.setText("Dinner:");

        lblBreakfast.setText("jLabel8");

        lblLunch.setText("jLabel8");

        lblDinner.setText("jLabel8");

        mnuMilitaryDiningHall.setText("Military Dining Hall");

        itmLogout.setText("Logout");
        itmLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmLogoutActionPerformed(evt);
            }
        });
        mnuMilitaryDiningHall.add(itmLogout);

        itmExit.setText("Exit");
        itmExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmExitActionPerformed(evt);
            }
        });
        mnuMilitaryDiningHall.add(itmExit);

        jMenuBar1.add(mnuMilitaryDiningHall);

        mnuAdministrationOfTheUsers.setText("Administration of the users");

        itmEditRegister.setText("Edit Register");
        itmEditRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmEditRegisterActionPerformed(evt);
            }
        });
        mnuAdministrationOfTheUsers.add(itmEditRegister);

        itmUpdateTheAccountBalanceForACommensal.setText("Upadate the account balance for a commensal");
        itmUpdateTheAccountBalanceForACommensal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmUpdateTheAccountBalanceForACommensalActionPerformed(evt);
            }
        });
        mnuAdministrationOfTheUsers.add(itmUpdateTheAccountBalanceForACommensal);

        jMenuBar1.add(mnuAdministrationOfTheUsers);

        mnuDayManagment.setText("Day Management");

        itmBookADay.setText("Book a Day");
        itmBookADay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmBookADayActionPerformed(evt);
            }
        });
        mnuDayManagment.add(itmBookADay);

        itmCancelADayBooking.setText("Cancel a Day Booking");
        itmCancelADayBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCancelADayBookingActionPerformed(evt);
            }
        });
        mnuDayManagment.add(itmCancelADayBooking);

        itmSeeReservation.setText("See reservation");
        itmSeeReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmSeeReservationActionPerformed(evt);
            }
        });
        mnuDayManagment.add(itmSeeReservation);

        jMenuBar1.add(mnuDayManagment);

        mnuHelp.setText("Help");
        jMenuBar1.add(mnuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDinner, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblLunch, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblBreakfast, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbldNameAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAccountBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(62, 62, 62))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldNameAdmin)
                    .addComponent(jLabel4)
                    .addComponent(lblAccountBalance)
                    .addComponent(jLabel2))
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblBreakfast))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblLunch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblDinner))
                .addContainerGap(124, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itmCancelADayBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCancelADayBookingActionPerformed
        // TODO add your handling code here:
        FrmCancelAppointment frmCancelAppoinment = new FrmCancelAppointment();
        this.setVisible(false);
        frmCancelAppoinment.setVisible(false);
    }//GEN-LAST:event_itmCancelADayBookingActionPerformed

    private void itmBookADayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmBookADayActionPerformed
        FrmBookDay frmBookDay = new FrmBookDay();
        this.setVisible(false);
        frmBookDay.setVisible(true);
    }//GEN-LAST:event_itmBookADayActionPerformed

    private void itmLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmLogoutActionPerformed
        FrmLogin frmLogin = new FrmLogin();
        this.setVisible(false);
        frmLogin.setVisible(true);

    }//GEN-LAST:event_itmLogoutActionPerformed

    private void itmExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_itmExitActionPerformed

    private void itmEditRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmEditRegisterActionPerformed
        // TODO add your handling code here:
        FrmEditRegister frmEditRegister = new FrmEditRegister();
        this.setVisible(false);
        frmEditRegister.setVisible(true);
    }//GEN-LAST:event_itmEditRegisterActionPerformed

    private void itmUpdateTheAccountBalanceForACommensalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmUpdateTheAccountBalanceForACommensalActionPerformed
        FrmUpdateAccountBalance frmUpdate = new FrmUpdateAccountBalance();
        this.setVisible(false);
        frmUpdate.setVisible(true);
    }//GEN-LAST:event_itmUpdateTheAccountBalanceForACommensalActionPerformed

    private void itmSeeReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmSeeReservationActionPerformed
        // TODO add your handling code here:
        FrmSeeAppointment frmSeeAppointmet = new FrmSeeAppointment();
        this.setVisible(false);
        frmSeeAppointmet.setVisible(true);
    }//GEN-LAST:event_itmSeeReservationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAdminMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JMenuItem itmBookADay;
    private javax.swing.JMenuItem itmCancelADayBooking;
    private javax.swing.JMenuItem itmEditRegister;
    private javax.swing.JMenuItem itmExit;
    private javax.swing.JMenuItem itmLogout;
    private javax.swing.JMenuItem itmSeeReservation;
    private javax.swing.JMenuItem itmUpdateTheAccountBalanceForACommensal;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lblAccountBalance;
    private javax.swing.JLabel lblBreakfast;
    private javax.swing.JLabel lblDinner;
    private javax.swing.JLabel lblLunch;
    private javax.swing.JLabel lbldNameAdmin;
    private javax.swing.JMenu mnuAdministrationOfTheUsers;
    private javax.swing.JMenu mnuDayManagment;
    private javax.swing.JMenu mnuHelp;
    private javax.swing.JMenu mnuMilitaryDiningHall;
    // End of variables declaration//GEN-END:variables
}
